repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-check
        args: [--fix]
        files: ^(benchmarks|docs|fastmob|fastmob-vis|scripts|tests)/.*\.(py|ipynb)$
  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
        files: ^(Cargo\.(toml|lock)|src/.*\.rs)$
