//! Bit-exact parity against the fastmob Python path.
//!
//! The fixtures under `tests/fixtures/` are generated by
//! `scripts/gen_rust_parity_fixtures.py`, which runs the Python implementation
//! and dumps its output. Equality here is *exact*, not approximate, on purpose:
//! a mathematically equivalent but differently-rounded Haversine was once shown
//! to reclassify 503 near-zero jumps on real data, which visibly shifted the
//! jump-length ECDF. A tolerance would have hidden that.

use std::path::{Path, PathBuf};

use fastmob_rs::{Cols, jump_lengths_flat, prepare, radius_of_gyration_flat};
use polars::prelude::*;

fn fixture_dir(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

fn read_f64_dump(path: &Path) -> Vec<f64> {
    let bytes = std::fs::read(path).unwrap_or_else(|err| panic!("read {}: {err}", path.display()));
    bytes
        .chunks_exact(8)
        .map(|chunk| f64::from_le_bytes(chunk.try_into().expect("8-byte chunk")))
        .collect()
}

fn read_input(path: &Path, string_uids: bool) -> DataFrame {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("read {}: {err}", path.display()));
    let mut uids_str = Vec::new();
    let mut uids_int = Vec::new();
    let mut datetimes = Vec::new();
    let mut lats = Vec::new();
    let mut lngs = Vec::new();

    for line in text.lines().skip(1) {
        let fields: Vec<&str> = line.split('\t').collect();
        assert_eq!(fields.len(), 4, "fixture rows have four columns");
        if string_uids {
            uids_str.push(fields[0].to_string());
        } else {
            uids_int.push(fields[0].parse::<i64>().expect("integer uid"));
        }
        datetimes.push(fields[1].to_string());
        lats.push(fields[2].parse::<f64>().expect("latitude"));
        lngs.push(fields[3].parse::<f64>().expect("longitude"));
    }

    let uid = if string_uids {
        Series::new("uid".into(), uids_str)
    } else {
        Series::new("uid".into(), uids_int)
    };
    DataFrame::new(vec![
        uid.into_column(),
        Series::new("datetime".into(), datetimes).into_column(),
        Series::new("lat".into(), lats).into_column(),
        Series::new("lng".into(), lngs).into_column(),
    ])
    .expect("fixture frame")
    .lazy()
    .with_column(col("datetime").str().to_datetime(
        Some(TimeUnit::Microseconds),
        None,
        StrptimeOptions {
            format: Some("%Y-%m-%dT%H:%M:%SZ".into()),
            strict: false,
            exact: true,
            cache: true,
        },
        lit("raise"),
    ))
    .drop_nulls(Some(cols(["datetime"])))
    .collect()
    .expect("parsed fixture frame")
}

fn assert_exact(name: &str, actual: &[f64], expected: &[f64]) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{name}: value count differs from the Python reference"
    );
    for (index, (got, want)) in actual.iter().zip(expected).enumerate() {
        assert!(
            got.to_bits() == want.to_bits(),
            "{name}: value {index} differs from the Python reference: got {got:?}, want {want:?}"
        );
    }
}

fn check_case(name: &str, string_uids: bool) {
    let dir = fixture_dir(name);
    let df = read_input(&dir.join("input.tsv"), string_uids);
    let prep = prepare(&df, Cols::auto()).expect("prepare");

    assert_exact(
        "jump_lengths",
        &jump_lengths_flat(&prep).expect("jump lengths"),
        &read_f64_dump(&dir.join("jump_lengths.f64")),
    );

    let (values, valid) = radius_of_gyration_flat(&prep);
    let rog: Vec<f64> = values
        .into_iter()
        .zip(valid)
        .filter_map(|(value, is_valid)| is_valid.then_some(value))
        .collect();
    assert_exact(
        "radius_of_gyration",
        &rog,
        &read_f64_dump(&dir.join("radius_of_gyration.f64")),
    );
}

#[test]
fn matches_python_on_brightkite_with_integer_uids() {
    check_case("brightkite_integer_uid", false);
}

/// Composite string ids (`"10_2980"`) are the case that broke when a port
/// parsed uids as integers: every user collapsed into one group, inventing
/// inter-user jumps. This fixture pins the correct behaviour.
#[test]
fn matches_python_on_brightkite_with_composite_string_uids() {
    check_case("brightkite_string_uid", true);
}
