[package]
name = "fastmob-py"
version = "0.1.1"
edition = "2024"
description = "PyO3 extension for fastmob mobility analysis."
license = "BSD-3-Clause"
repository = "https://github.com/gefgu/fastmob"

[lib]
name = "fastmob"
crate-type = ["cdylib"]

[dependencies]
fastmob-core = { path = "../fastmob-core", default-features = false }
pyo3 = "0.28.2"
numpy = "0.28.0"
pyo3-arrow = "0.17.0"
arrow-array = "58.1.0"

[features]
default = ["simd"]
simd = ["numkong", "stvd-emd"]
numkong = ["fastmob-core/numkong"]
stvd-emd = ["fastmob-core/stvd-emd"]
